### ISSUE TITLE
updated wiki, Merge required

### ISSUE THREAD

**Issue by ghost** [Team-SDIoT/SDIoT_Events#1]

**Comment by git-akshay** [comment]
Update wiki for SDIoT

**Comment by ghost** [comment]
Here is the link to update wiki:
https://github.com/git-akshay/SDIoT_Events.wiki.git

Please refer this when attempting merge:
https://gist.github.com/larrybotha/10650410

**Comment by iayanpahwa** [comment]
@git-akshay I cant access the link [https://github.com/git-akshay/SDIoT_Events.wiki.git](url) 
Also you dont require permissions to do so, work on your local form and push chnages there in comits, when done raise a PR on main repo from your fork, I'll review and merge the changes!

**Comment by ghost** [comment]
@iayanpahwa To update wiki of the repo, I need to open wiki tab. but it is not accessible.
I am trying to open wiki using this link:
https://github.com/Team-SDIoT/SDIoT_Events/wiki
which opens up this:
https://github.com/Team-SDIoT/SDIoT_Events

Maybe you need to create a wiki page so that I can clone it and start editing.
